spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:/github/spatial-grid-data-engine/src/test/resources/test.sqlite
    username:
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    database-platform: com.xidian.spatial.configuration.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      force: true
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      max-idle: 8
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

logging:
  # 配置日志类型
  level:
    com.xidian.spatial: debug

mybatis:
  type-aliases-package: com.xidian.domain
  mapper-locations: classpath:repository/*.xml
  config-location: classpath:mybatis-config.xml

user:
  name: XiDian-ChenMiao
  email: daqinzhidi@163.com

